language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: false
      jdk: openjdk8

script: ./mvnw clean test -DlocalRessources.ressourcePathDirectory=`pwd`/src/main/resources/json/LocalRessources
